const TIMING_FUNCTIONS = ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end"];

const COMMON_DURATION = ["0s", "0.1s", "0.2s", "0.3s", "0.4s", "0.5s", "0.6s", "0.7s", "0.8s", "0.9s", "1s"];

const GRADIENT_TYPES = [
	"linear-gradient",
	"repeating-linear-gradient",
	"radial-gradient",
	"repeating-radial-gradient",
];

const BORDER_OUTLINE_STYLE = [
	"auto",
	"none",
	"dotted",
	"dashed",
	"solid",
	"double",
	"groove",
	"ridge",
	"inset",
	"outset",
];

const EXTENDED_PROPERTIES = {
	border: BORDER_OUTLINE_STYLE,
	outline: BORDER_OUTLINE_STYLE,
	background: [
		"repeat",
		"repeat-x",
		"repeat-y",
		"no-repeat",
		"fixed",
		"scroll",
		"local",
		"border-box",
		"padding-box",
		"content-box",
		...GRADIENT_TYPES,
	],
	"list-style-type": [
		"disc",
		"armenian",
		"circle",
		"cjk-ideographic",
		"decimal",
		"decimal-leading-zero",
		"georgian",
		"hebrew",
		"hiragana",
		"hiragana-iroha",
		"katakana",
		"katakana-iroha",
		"lower-alpha",
		"lower-greek",
		"lower-latin",
		"lower-roman",
		"none",
		"square",
		"upper-alpha",
		"upper-greek",
		"upper-latin",
		"upper-roman",
		"initial",
		"inherit",
	],
	"list-style-position": ["inside", "outside", "initial", "inherit"],
	"list-style-image": ["none", "url", "initial", "inherit"],
	transition: ["none", "all", "property", "initial", "inherit", ...COMMON_DURATION, ...TIMING_FUNCTIONS],
};

export const cssReference = {
	padding: {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	margin: {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	background: {
		initial: "see individual properties",
		values: [
			"[prop:background-color]",
			"[prop:background-image]",
			"[prop:background-position]",
			"[prop:background-size]",
			"[prop:background-repeat]",
			"[prop:background-origin]",
			"[prop:background-clip]",
			"[prop:background-attachment]",
			"initial",
			"inherit",
			...EXTENDED_PROPERTIES.background,
		],
	},
	color: {
		initial: "not specified",
		values: ["[color]", "initial", "inherit"],
	},
	font: {
		initial: "The default value of the font properties",
		values: [
			"[prop:font-style]",
			"[prop:font-variant]",
			"[prop:font-weight]",
			"[prop:font-size/line-height]",
			"[prop:font-family]",
			"caption",
			"icon",
			"menu",
			"message-box",
			"small-caption",
			"status-bar",
			"initial",
			"inherit",
		],
	},
	"font-size": {
		initial: "medium",
		values: [
			"medium",
			"xx-small",
			"x-small",
			"small",
			"large",
			"x-large",
			"xx-large",
			"smaller",
			"larger",
			"[length]",
			"[percent]",
			"initial",
			"inherit",
		],
	},
	"border-bottom": {
		initial: "medium none color",
		values: [
			"[prop:border-bottom-width]",
			"[prop:border-bottom-style]",
			"[prop:border-bottom-color]",
			"initial",
			"inherit",
		],
	},
	"align-content": {
		initial: "stretch",
		values: [
			"stretch",
			"center",
			"flex-start",
			"flex-end",
			"space-between",
			"space-around",
			"initial",
			"inherit",
		],
	},
	"align-items": {
		initial: "stretch",
		values: ["stretch", "center", "flex-start", "flex-end", "baseline", "initial", "inherit"],
	},
	"align-self": {
		initial: "auto",
		values: ["auto", "stretch", "center", "flex-start", "flex-end", "baseline", "initial", "inherit"],
	},
	all: {
		initial: "none",
		values: ["initial", "inherit", "unset"],
	},
	animation: {
		initial: "none 0 ease 0 1 normal none running",
		values: [
			"[prop:animation-name]",
			"[prop:animation-duration]",
			"[prop:animation-timing-function]",
			"[prop:animation-delay]",
			"[prop:animation-iteration-count]",
			"[prop:animation-direction]",
			"[prop:animation-fill-mode]",
			"[prop:animation-play-state]",
			"initial",
			"inherit",
			...TIMING_FUNCTIONS,
			...COMMON_DURATION,
		],
	},
	"animation-delay": {
		initial: "0s",
		values: ["[time]", "initial", "inherit", ...COMMON_DURATION],
	},
	"animation-direction": {
		initial: "normal",
		values: ["normal", "reverse", "alternate", "alternate-reverse", "initial", "inherit"],
	},
	"animation-duration": {
		initial: "0",
		values: ["[time]", "initial", "inherit", ...COMMON_DURATION],
	},
	"animation-fill-mode": {
		initial: "none",
		values: ["none", "forwards", "backwards", "both", "initial", "inherit"],
	},
	"animation-iteration-count": {
		initial: "1",
		values: ["[number]", "infinite", "initial", "inherit"],
	},
	"animation-name": {
		initial: "none",
		values: ["[label]", "none", "initial", "inherit"],
	},
	"animation-play-state": {
		initial: "running",
		values: ["paused", "running", "initial", "inherit"],
	},
	"animation-timing-function": {
		initial: "ease",
		values: [
			"linear",
			"ease",
			"ease-in",
			"ease-out",
			"ease-in-out",
			"step-start",
			"step-end",
			"[steps]",
			"cubic-bezier",
			"initial",
			"inherit",
		],
	},
	"backface-visibility": {
		initial: "visible",
		values: ["visible", "hidden", "initial", "inherit"],
	},
	"background-attachment": {
		initial: "scroll",
		values: ["scroll", "fixed", "local", "initial", "inherit"],
	},
	"background-blend-mode": {
		initial: "normal",
		values: [
			"normal",
			"multiply",
			"screen",
			"overlay",
			"darken",
			"lighten",
			"color-dodge",
			"saturation",
			"[color]",
			"luminosity",
		],
	},
	"background-clip": {
		initial: "border-box",
		values: ["border-box", "padding-box", "content-box", "initial", "inherit"],
	},
	"background-color": {
		initial: "transparent",
		values: ["[color]", "transparent", "initial", "inherit"],
	},
	"background-image": {
		initial: "none",
		values: ["none", "initial", "inherit"],
	},
	"background-origin": {
		initial: "padding-box",
		values: ["padding-box", "border-box", "content-box", "initial", "inherit"],
	},
	"background-position": {
		initial: "0% 0%",
		values: [
			"left top",
			"left center",
			"left bottom",
			"right top",
			"right center",
			"right bottom",
			"center top",
			"center center",
			"center bottom",
			"([percent]){2,2}",
			"([length]){2,2}",
			"initial",
			"inherit",
		],
	},
	"background-repeat": {
		initial: "repeat",
		values: ["repeat", "repeat-x", "repeat-y", "no-repeat", "space", "round", "initial", "inherit"],
	},
	"background-size": {
		initial: "auto",
		values: ["auto", "[length]", "percentage", "cover", "contain", "initial", "inherit"],
	},
	border: {
		initial: "medium none color",
		values: [
			"[prop:border-width]",
			"[prop:border-style]",
			"[prop:border-color]",
			"initial",
			"inherit",
			...EXTENDED_PROPERTIES.border,
		],
	},
	"border-bottom-color": {
		initial: "The current color of the element",
		values: ["[color]", "transparent", "initial", "inherit"],
	},
	"border-bottom-left-radius": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"border-bottom-right-radius": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"border-bottom-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"border-bottom-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	"border-collapse": {
		initial: "separate",
		values: ["separate", "collapse", "initial", "inherit"],
	},
	"border-color": {
		initial: "The current color of the element",
		values: ["[color]", "transparent", "initial", "inherit"],
	},
	"border-image": {
		initial: "none 100% 1 0 stretch",
		values: [
			"[prop:border-image-source]",
			"[prop:border-image-slice]",
			"[prop:border-image-width]",
			"[prop:border-image-outset]",
			"[prop:border-image-repeat]",
			"initial",
			"inherit",
		],
	},
	"border-image-outset": {
		initial: "0",
		values: ["[length]", "[number]", "initial", "inherit"],
	},
	"border-image-repeat": {
		initial: "stretch",
		values: ["stretch", "repeat", "round", "space", "initial", "inherit"],
	},
	"border-image-slice": {
		initial: "100%",
		values: ["[number]", "[percent]", "fill", "initial", "inherit"],
	},
	"border-image-source": {
		initial: "none",
		values: ["none", "image", "initial", "inherit"],
	},
	"border-image-width": {
		initial: "1",
		values: ["[length]", "[number]", "[percent]", "auto", "initial", "inherit"],
	},
	"border-left": {
		initial: "medium none color",
		values: [
			"[prop:border-left-width]",
			"[prop:border-left-style]",
			"[prop:border-left-color]",
			"initial",
			"inherit",
		],
	},
	"border-left-color": {
		initial: "The current color of the element",
		values: ["[color]", "transparent", "initial", "inherit"],
	},
	"border-left-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"border-left-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	"border-radius": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"border-right": {
		initial: "medium none color",
		values: [
			"[prop:border-right-width]",
			"[prop:border-right-style]",
			"[prop:border-right-color]",
			"initial",
			"inherit",
		],
	},
	"border-right-color": {
		initial: "black",
		values: ["[color]", "transparent", "initial", "inherit"],
	},
	"border-right-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"border-right-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	"border-spacing": {
		initial: "2px",
		values: ["[length]", "initial", "inherit"],
	},
	"border-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"border-top": {
		initial: "medium none color",
		values: [
			"[prop:border-top-width]",
			"[prop:border-top-style]",
			"[prop:border-top-color]",
			"initial",
			"inherit",
		],
	},
	"border-top-color": {
		initial: "The current color of the element",
		values: ["[color]", "transparent", "initial", "inherit"],
	},
	"border-top-left-radius": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"border-top-right-radius": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"border-top-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"border-top-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	"border-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	bottom: {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"inset-block-end": {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"box-decoration-break": {
		initial: "slice",
		values: ["slice", "clone", "initial", "inherit"],
	},
	"box-shadow": {
		initial: "none",
		values: ["none", "h-offset", "v-offset", "blur", "spread", "[color]", "inset", "initial", "inherit"],
	},
	"box-sizing": {
		initial: "content-box",
		values: ["content-box", "border-box", "initial", "inherit"],
	},
	"caption-side": {
		initial: "top",
		values: ["top", "bottom", "initial", "inherit"],
	},
	"caret-color": {
		initial: "auto",
		values: ["auto", "[color]"],
	},
	"@charset": {
		initial: "charset",
		values: ["charset"],
	},
	clear: {
		initial: "none",
		values: ["none", "left", "right", "both", "initial", "inherit"],
	},
	clip: {
		initial: "auto",
		values: ["auto", "shape", "initial", "inherit"],
	},
	"column-count": {
		initial: "auto",
		values: ["[number]", "auto", "initial", "inherit"],
	},
	"column-fill": {
		initial: "balance",
		values: ["balance", "auto", "initial", "inherit"],
	},
	"column-gap": {
		initial: "normal",
		values: ["[length]", "normal", "initial", "inherit"],
	},
	"column-rule": {
		initial: "medium none color",
		values: [
			"[prop:column-rule-width]",
			"[prop:column-rule-style]",
			"[prop:column-rule-color]",
			"initial",
			"inherit",
		],
	},
	"column-rule-color": {
		initial: "The current color of the element",
		values: ["[color]", "initial", "inherit"],
	},
	"column-rule-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"column-rule-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	"column-span": {
		initial: "none",
		values: ["none", "all", "initial", "inherit"],
	},
	"column-width": {
		initial: "auto",
		values: ["auto", "[length]", "initial", "inherit"],
	},
	columns: {
		initial: "auto auto",
		values: ["auto", "[prop:column-width]", "[prop:column-count]", "initial", "inherit"],
	},
	content: {
		initial: "normal",
		values: [
			"normal",
			"none",
			"counter",
			"attr(attribute)",
			"string",
			"open-quote",
			"close-quote",
			"no-open-quote",
			"no-close-quote",
			"url(url)",
			"initial",
			"inherit",
		],
	},
	"counter-increment": {
		initial: "none",
		values: ["none", "[number]", "initial", "inherit"],
	},
	"counter-reset": {
		initial: "none",
		values: ["none", "[number]", "initial", "inherit"],
	},
	cursor: {
		initial: "auto",
		values: [
			"alias",
			"all-scroll",
			"auto",
			"cell",
			"context-menu",
			"col-resize",
			"copy",
			"crosshair",
			"default",
			"e-resize",
			"ew-resize",
			"grab",
			"grabbing",
			"help",
			"move",
			"n-resize",
			"ne-resize",
			"nesw-resize",
			"ns-resize",
			"nw-resize",
			"nwse-resize",
			"no-drop",
			"none",
			"not-allowed",
			"pointer",
			"progress",
			"row-resize",
			"s-resize",
			"se-resize",
			"sw-resize",
			"text",
			"URL",
			"vertical-text",
			"w-resize",
			"wait",
			"zoom-in",
			"zoom-out",
			"initial",
			"inherit",
		],
	},
	direction: {
		initial: "ltr",
		values: ["ltr", "rtl", "initial", "inherit"],
	},
	display: {
		initial: "",
		values: [
			"inline",
			"block",
			"contents",
			"flex",
			"grid",
			"inline-block",
			"inline-flex",
			"inline-grid",
			"inline-table",
			"list-item",
			"run-in",
			"table",
			"table-caption",
			"table-column-group",
			"table-header-group",
			"table-footer-group",
			"table-row-group",
			"table-cell",
			"table-column",
			"table-row",
			"none",
			"initial",
			"inherit",
		],
	},
	"empty-cells": {
		initial: "show",
		values: ["show", "hide", "initial", "inherit"],
	},
	filter: {
		initial: "none",
		values: ["none", "initial", "inherit"],
	},
	flex: {
		initial: "0 1 auto",
		values: [
			"[prop:flex-grow]",
			"[prop:flex-shrink]",
			"[prop:flex-basis]",
			"auto",
			"initial",
			"none",
			"inherit",
		],
	},
	"flex-basis": {
		initial: "auto",
		values: ["[number]", "auto", "initial", "inherit"],
	},
	"flex-direction": {
		initial: "row",
		values: ["row", "row-reverse", "column", "column-reverse", "initial", "inherit"],
	},
	"flex-flow": {
		initial: "row nowrap",
		values: ["flex-direction", "flex-wrap", "initial", "inherit"],
	},
	"flex-grow": {
		initial: "0",
		values: ["[number]", "initial", "inherit"],
	},
	"flex-shrink": {
		initial: "1",
		values: ["[number]", "initial", "inherit"],
	},
	"flex-wrap": {
		initial: "nowrap",
		values: ["nowrap", "wrap", "wrap-reverse", "initial", "inherit"],
	},
	float: {
		initial: "none",
		values: ["none", "left", "right", "initial", "inherit"],
	},
	"font-family": {
		initial: "depends on the browser",
		values: ["[family-name]", "[generic-family]", "initial", "inherit"],
	},
	"font-kerning": {
		initial: "auto",
		values: ["auto", "normal", "none"],
	},
	"font-size-adjust": {
		initial: "none",
		values: ["[number]", "none", "initial", "inherit"],
	},
	"font-stretch": {
		initial: "normal",
		values: [
			"ultra-condensed",
			"extra-condensed",
			"condensed",
			"semi-condensed",
			"normal",
			"semi-expanded",
			"expanded",
			"extra-expanded",
			"ultra-expanded",
			"initial",
			"inherit",
		],
	},
	"font-style": {
		initial: "normal",
		values: ["normal", "italic", "oblique", "initial", "inherit"],
	},
	"font-variant": {
		initial: "normal",
		values: ["normal", "small-caps", "initial", "inherit"],
	},
	"font-weight": {
		initial: "normal",
		values: [
			"normal",
			"bold",
			"bolder",
			"lighter",
			"100",
			"200",
			"300",
			"400",
			"500",
			"600",
			"700",
			"800",
			"900",
			"initial",
			"inherit",
		],
	},
	gap: {
		initial: "none",
		values: ["[length]", "initial", "inherit"],
	},
	grid: {
		initial: "none none none auto auto row",
		values: [
			"none",
			"grid-template rows / grid-template-columns",
			"grid-template-areas",
			"grid-template rows / grid-auto-columns",
			"grid-auto-rows / grid-template-columns",
			"grid-template rows / grid-auto-flow grid-auto-columns",
			"grid-auto flow grid-auto-rows / grid-template-columns",
			"initial",
			"inherit",
		],
	},
	"grid-area": {
		initial: "auto / auto / auto / auto",
		values: [
			"[prop:grid-row-start]",
			"[prop:grid-column-start]",
			"[prop:grid-row-end]",
			"[prop:grid-column-end]",
			"[label]",
		],
	},
	"grid-auto-columns": {
		initial: "auto",
		values: ["auto", "max-content", "min-content", "[length]", "[percent]"],
	},
	"grid-auto-flow": {
		initial: "row",
		values: ["row", "column", "dense", "row dense", "column dense"],
	},
	"grid-auto-rows": {
		initial: "auto",
		values: ["auto", "max-content", "min-content", "[length]"],
	},
	"grid-column": {
		initial: "auto / auto",
		values: ["[prop:grid-column-start]", "[prop:grid-column-end]"],
	},
	"grid-column-end": {
		initial: "auto",
		values: ["auto", "(span) ([number])", "column-line"],
	},
	"grid-column-gap": {
		initial: "0",
		values: ["[length]"],
	},
	"grid-column-start": {
		initial: "auto",
		values: ["auto", "(span) ([number])", "column-line"],
	},
	"grid-gap": {
		initial: "0 0",
		values: ["[prop:grid-row-gap]", "[prop:grid-column-gap]"],
	},
	"grid-row": {
		initial: "auto / auto",
		values: ["[prop:grid-row-start]", "[prop:grid-row-end]"],
	},
	"grid-row-end": {
		initial: "auto",
		values: ["auto", "(span) ([number])", "column-line"],
	},
	"grid-row-gap": {
		initial: "0",
		values: ["[length]"],
	},
	"grid-row-start": {
		initial: "auto",
		values: ["auto", "row-line"],
	},
	"grid-template": {
		initial: "none none none",
		values: [
			"none",
			"grid-template rows / grid-template-columns",
			"grid-template-areas",
			"initial",
			"inherit",
		],
	},
	"grid-template-areas": {
		initial: "none",
		values: ["none", "itemnames"],
	},
	"grid-template-columns": {
		initial: "none",
		values: ["none", "auto", "max-content", "min-content", "[length]", "initial", "inherit"],
	},
	"grid-template-rows": {
		initial: "none",
		values: ["none", "auto", "max-content", "min-content", "[length]"],
	},
	"hanging-punctuation": {
		initial: "none",
		values: ["none", "first", "last", "allow-end", "force-end", "initial", "inherit"],
	},
	height: {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	hyphens: {
		initial: "manual",
		values: ["none", "manual", "auto", "initial", "inherit"],
	},
	isolation: {
		initial: "auto",
		values: ["auto", "isolate", "initial", "inherit"],
	},
	"justify-content": {
		initial: "flex-start",
		values: ["flex-start", "flex-end", "center", "space-between", "space-around", "initial", "inherit"],
	},
	left: {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"inset-inline-start": {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"letter-spacing": {
		initial: "normal",
		values: ["normal", "[length]", "initial", "inherit"],
	},
	"line-height": {
		initial: "normal",
		values: ["normal", "[number]", "[length]", "[percent]", "initial", "inherit"],
	},
	"list-style": {
		initial: "disc outside none",
		values: [
			"[prop:list-style-type]",
			"[prop:list-style-position]",
			"[prop:list-style-image]",
			"initial",
			"inherit",
			...EXTENDED_PROPERTIES["list-style-type"],
			...EXTENDED_PROPERTIES["list-style-position"],
			...EXTENDED_PROPERTIES["list-style-image"],
		],
	},
	"list-style-image": {
		initial: "none",
		values: ["none", "url", "initial", "inherit"],
	},
	"list-style-position": {
		initial: "outside",
		values: ["inside", "outside", "initial", "inherit"],
	},
	"list-style-type": {
		initial: "disc",
		values: [
			"disc",
			"armenian",
			"circle",
			"cjk-ideographic",
			"decimal",
			"decimal-leading-zero",
			"georgian",
			"hebrew",
			"hiragana",
			"hiragana-iroha",
			"katakana",
			"katakana-iroha",
			"lower-alpha",
			"lower-greek",
			"lower-latin",
			"lower-roman",
			"none",
			"square",
			"upper-alpha",
			"upper-greek",
			"upper-latin",
			"upper-roman",
			"initial",
			"inherit",
		],
	},
	"margin-bottom": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-left": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-right": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-top": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-block-start": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-block-end": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-inline-start": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"margin-inline-end": {
		initial: "0",
		values: ["[length]", "[percent]", "auto", "initial", "inherit"],
	},
	"max-height": {
		initial: "none",
		values: ["none", "[length]", "[percent]", "initial", "inherit"],
	},
	"max-width": {
		initial: "none",
		values: ["none", "[length]", "[percent]", "initial", "inherit"],
	},
	"min-height": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"min-width": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"mix-blend-mode": {
		initial: "normal",
		values: [
			"normal",
			"multiply",
			"screen",
			"overlay",
			"darken",
			"lighten",
			"color-dodge",
			"color-burn",
			"difference",
			"exclusion",
			"hue",
			"saturation",
			"[color]",
			"luminosity",
		],
	},
	"object-fit": {
		initial: "",
		values: ["fill", "contain", "cover", "none", "scale-down", "initial", "inherit"],
	},
	"object-position": {
		initial: "50% 50%",
		values: ["position", "initial", "inherit"],
	},
	opacity: {
		initial: "1",
		values: ["[number]", "initial", "inherit"],
	},
	order: {
		initial: "0",
		values: ["[number]", "initial", "inherit"],
	},
	outline: {
		initial: "medium invert color",
		values: [
			"[prop:outline-width]",
			"[prop:outline-style]",
			"[prop:outline-color]",
			"initial",
			"inherit",
			...EXTENDED_PROPERTIES.outline,
		],
	},
	"outline-color": {
		initial: "invert",
		values: ["invert", "[color]", "initial", "inherit"],
	},
	"outline-offset": {
		initial: "0",
		values: ["[length]", "initial", "inherit"],
	},
	"outline-style": {
		initial: "none",
		values: [
			"none",
			"hidden",
			"dotted",
			"dashed",
			"solid",
			"double",
			"groove",
			"ridge",
			"inset",
			"outset",
			"initial",
			"inherit",
		],
	},
	"outline-width": {
		initial: "medium",
		values: ["medium", "thin", "thick", "[length]", "initial", "inherit"],
	},
	overflow: {
		initial: "visible",
		values: ["visible", "hidden", "scroll", "auto", "initial", "inherit"],
	},
	"overflow-x": {
		initial: "visible",
		values: ["visible", "hidden", "scroll", "auto", "initial", "inherit"],
	},
	"overflow-y": {
		initial: "visible",
		values: ["visible", "hidden", "scroll", "auto", "initial", "inherit"],
	},
	"padding-bottom": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-left": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-right": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-top": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-block-start": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-block-end": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-inline-start": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"padding-inline-end": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"page-break-after": {
		initial: "auto",
		values: ["auto", "always", "avoid", "left", "right", "initial", "inherit"],
	},
	"page-break-before": {
		initial: "auto",
		values: ["auto", "always", "avoid", "left", "right", "initial", "inherit"],
	},
	"page-break-inside": {
		initial: "auto",
		values: ["auto", "avoid", "initial", "inherit"],
	},
	perspective: {
		initial: "none",
		values: ["[length]", "none", "initial", "inherit"],
	},
	"perspective-origin": {
		initial: "50% 50%",
		values: ["x-axis", "y-axis", "initial", "inherit"],
	},
	"pointer-events": {
		initial: "auto",
		values: ["auto", "none", "initial", "inherit"],
	},
	position: {
		initial: "static",
		values: ["static", "absolute", "fixed", "relative", "sticky", "initial", "inherit"],
	},
	quotes: {
		initial: "not specified",
		values: [
			"none",
			"string string string string",
			"initial",
			"inherit",
			'"',
			"'",
			"‹",
			"›",
			"«",
			"»",
			"‘",
			"’",
			"“",
			"”",
			"„",
		],
	},
	resize: {
		initial: "none",
		values: ["none", "both", "horizontal", "vertical", "initial", "inherit"],
	},
	right: {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"inset-inline-end": {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"scroll-behavior": {
		initial: "auto",
		values: ["auto", "smooth", "initial", "inherit"],
	},
	"tab-size": {
		initial: "8",
		values: ["[number]", "[length]", "initial", "inherit"],
	},
	"table-layout": {
		initial: "auto",
		values: ["auto", "fixed", "initial", "inherit"],
	},
	"text-align": {
		initial: "left if direction is ltr, and right if direction is rtl",
		values: ["left", "right", "center", "justify", "initial", "inherit"],
	},
	"text-align-last": {
		initial: "auto",
		values: ["auto", "left", "right", "center", "justify", "start", "end", "initial", "inherit"],
	},
	"text-decoration": {
		initial: "none currentcolor solid",
		values: [
			"[prop:text-decoration-line]",
			"[prop:text-decoration-color]",
			"[prop:text-decoration-style]",
			"initial",
			"inherit",
		],
	},
	"text-decoration-color": {
		initial: "currentColor",
		values: ["[color]", "initial", "inherit"],
	},
	"text-decoration-line": {
		initial: "none",
		values: ["none", "underline", "overline", "line-through", "initial", "inherit"],
	},
	"text-decoration-style": {
		initial: "solid",
		values: ["solid", "double", "dotted", "dashed", "wavy", "initial", "inherit"],
	},
	"text-indent": {
		initial: "0",
		values: ["[length]", "[percent]", "initial", "inherit"],
	},
	"text-justify": {
		initial: "auto",
		values: ["auto", "inter-word", "inter-character", "none", "initial", "inherit"],
	},
	"text-overflow": {
		initial: "clip",
		values: ["clip", "ellipsis", "string", "initial", "inherit"],
	},
	"text-shadow": {
		initial: "none",
		values: ["h-shadow", "v-shadow", "blur-radius", "[color]", "none", "initial", "inherit"],
	},
	"text-transform": {
		initial: "none",
		values: ["none", "capitalize", "uppercase", "lowercase", "initial", "inherit"],
	},
	top: {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"inset-block-start": {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	transform: {
		initial: "none",
		values: ["none", "initial", "inherit"],
	},
	"transform-origin": {
		initial: "50% 50% 0",
		values: ["x-axis", "y-axis", "z-axis", "initial", "inherit"],
	},
	"transform-style": {
		initial: "flat",
		values: ["flat", "preserve-3d", "initial", "inherit"],
	},
	transition: {
		initial: "all 0s ease 0s",
		values: [
			"[prop:transition-property]",
			"[prop:transition-duration]",
			"[prop:transition-timing-function]",
			"[prop:transition-delay]",
			"initial",
			"inherit",
			...EXTENDED_PROPERTIES.transition,
		],
	},
	"transition-delay": {
		initial: "0s",
		values: ["[time]", "initial", "inherit", ...COMMON_DURATION],
	},
	"transition-duration": {
		initial: "0s",
		values: ["[time]", "initial", "inherit", ...COMMON_DURATION],
	},
	"transition-property": {
		initial: "all",
		values: ["none", "all", "property", "initial", "inherit"],
	},
	"transition-timing-function": {
		initial: "ease",
		values: [
			"ease",
			"linear",
			"ease-in",
			"ease-out",
			"ease-in-out",
			"step-start",
			"step-end",
			"initial",
			"inherit",
		],
	},
	"unicode-bidi": {
		initial: "normal",
		values: [
			"normal",
			"embed",
			"bidi-override",
			"isolate",
			"isolate-override",
			"plaintext",
			"initial",
			"inherit",
		],
	},
	"user-select": {
		initial: "auto",
		values: ["auto", "none", "text", "all"],
	},
	"vertical-align": {
		initial: "baseline",
		values: [
			"baseline",
			"[length]",
			"[percent]",
			"sub",
			"super",
			"top",
			"text-top",
			"middle",
			"bottom",
			"text-bottom",
			"initial",
			"inherit",
		],
	},
	visibility: {
		initial: "visible",
		values: ["visible", "hidden", "collapse", "initial", "inherit"],
	},
	"white-space": {
		initial: "normal",
		values: ["normal", "nowrap", "pre", "pre-line", "pre-wrap", "initial", "inherit"],
	},
	width: {
		initial: "auto",
		values: ["auto", "[length]", "[percent]", "initial", "inherit"],
	},
	"word-break": {
		initial: "normal",
		values: ["normal", "break-all", "keep-all ", "break-word", "initial", "inherit"],
	},
	"word-spacing": {
		initial: "normal",
		values: ["normal", "[length]", "initial", "inherit"],
	},
	"word-wrap": {
		initial: "normal",
		values: ["normal", "break-word", "initial", "inherit"],
	},
	"writing-mode": {
		initial: "horizontal-tb",
		values: ["horizontal-tb", "vertical-rl", "vertical-lr"],
	},
	"z-index": {
		initial: "auto",
		values: ["auto", "[number]", "initial", "inherit"],
	},
	"backdrop-filter": {
		initial: "none",
		values: ["none", "initial", "inherit"],
	},
};

export const cssLogicalPropsMap = new Map([
	["inset-block-start", "top"],
	["inset-inline-start", "left"],
	["inset-inline-end", "right"],
	["inset-block-end", "bottom"],
	["margin-block-start", "margin-top"],
	["margin-block-end", "margin-bottom"],
	["margin-inline-start", "margin-left"],
	["margin-inline-end", "margin-right"],
	["padding-block-start", "padding-top"],
	["padding-block-end", "padding-bottom"],
	["padding-inline-start", "padding-left"],
	["padding-inline-end", "padding-right"],
]);

export const PROPERTIES = Object.keys(cssReference);
